// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHeB1vEUolHHCH4y25LRUiez33ETPCyEU',
    appId: '1:493648790490:web:dcba842c58b76967c936e3',
    messagingSenderId: '493648790490',
    projectId: 'diplomawork-7de70',
    authDomain: 'diplomawork-7de70.firebaseapp.com',
    storageBucket: 'diplomawork-7de70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBymVi6S-9ns77HrC3AI4AlPMRFMGjLVEo',
    appId: '1:493648790490:android:f03ff7ab09e29a3fc936e3',
    messagingSenderId: '493648790490',
    projectId: 'diplomawork-7de70',
    storageBucket: 'diplomawork-7de70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcLW-Hk-wZ08vWM0I6fvFjxmj9tY2IdeI',
    appId: '1:493648790490:ios:0c7d0b840037b6c3c936e3',
    messagingSenderId: '493648790490',
    projectId: 'diplomawork-7de70',
    storageBucket: 'diplomawork-7de70.appspot.com',
    iosBundleId: 'com.example.llf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcLW-Hk-wZ08vWM0I6fvFjxmj9tY2IdeI',
    appId: '1:493648790490:ios:c3644f372fdd7670c936e3',
    messagingSenderId: '493648790490',
    projectId: 'diplomawork-7de70',
    storageBucket: 'diplomawork-7de70.appspot.com',
    iosBundleId: 'com.example.llf.RunnerTests',
  );
}
